package org.microproxy;

import java.net.InetSocketAddress;
import org.microproxy.http.HttpObject;
import org.microproxy.http.HttpResponse;

/**
 * Hooks into the life of a single request/response exchange. One instance is created per request
 * by {@link HttpFiltersSource#filterRequest}; all methods are invoked on the virtual thread that
 * serves the client connection, so implementations may block.
 *
 * <p>Unless the {@link HttpFiltersSource} asks for buffering, a message flows through the filter
 * as a head ({@link org.microproxy.http.HttpRequest}/{@link org.microproxy.http.HttpResponse})
 * followed by zero or more {@link org.microproxy.http.HttpContent} pieces and a final {@link
 * org.microproxy.http.LastHttpContent}. With buffering it arrives as a single {@link
 * org.microproxy.http.FullHttpRequest}/{@link org.microproxy.http.FullHttpResponse}.
 *
 * <p>Every method has a no-op default, so implement only what you need. Call order for a typical
 * exchange:
 *
 * <ol>
 *   <li>{@link #clientToProxyRequest}
 *   <li>{@link #proxyToServerResolutionStarted}, {@link #proxyToServerResolutionSucceeded} /
 *       {@link #proxyToServerResolutionFailed}
 *   <li>{@link #proxyToServerConnectionStarted}, {@link
 *       #proxyToServerConnectionSSLHandshakeStarted}, {@link #proxyToServerConnectionSucceeded} /
 *       {@link #proxyToServerConnectionFailed}
 *   <li>{@link #proxyToServerRequest}, {@link #proxyToServerRequestSending}, {@link
 *       #proxyToServerRequestSent}
 *   <li>{@link #serverToProxyResponseReceiving}, {@link #serverToProxyResponse}, {@link
 *       #serverToProxyResponseReceived} (or {@link #serverToProxyResponseTimedOut})
 *   <li>{@link #proxyToClientResponse}
 * </ol>
 */
public interface HttpFilters {

    /**
     * Filters requests on their way from the client to the proxy. Return a response to answer the
     * client directly ("short-circuit") without contacting the server; only the return value for
     * the request head is honoured.
     */
    default HttpResponse clientToProxyRequest(HttpObject httpObject) {
        return null;
    }

    /**
     * Filters requests on their way from the proxy to the server, after the proxy has rewritten
     * headers. Return a response to short-circuit; only the return value for the request head is
     * honoured.
     */
    default HttpResponse proxyToServerRequest(HttpObject httpObject) {
        return null;
    }

    /** Called just before the request head is written to the server. */
    default void proxyToServerRequestSending() {}

    /** Called after the complete request, including its body, has been written to the server. */
    default void proxyToServerRequestSent() {}

    /**
     * Filters responses on their way from the server to the proxy. Return the (possibly modified
     * or replaced) object, or {@code null} to abort and disconnect the client.
     */
    default HttpObject serverToProxyResponse(HttpObject httpObject) {
        return httpObject;
    }

    /** Called when the server did not respond within the idle timeout. */
    default void serverToProxyResponseTimedOut() {}

    /** Called when the server begins sending a response. */
    default void serverToProxyResponseReceiving() {}

    /** Called when the server has finished sending a response. */
    default void serverToProxyResponseReceived() {}

    /**
     * Filters responses on their way from the proxy to the client. This also sees responses
     * generated by the proxy itself (errors, short-circuits, the CONNECT 200). Return the (possibly
     * modified) object, or {@code null} to abort and disconnect the client.
     */
    default HttpObject proxyToClientResponse(HttpObject httpObject) {
        return httpObject;
    }

    /**
     * Called before the server's host name is resolved. Return an address to skip resolution and
     * connect there instead.
     */
    default InetSocketAddress proxyToServerResolutionStarted(String resolvingServerHostAndPort) {
        return null;
    }

    default void proxyToServerResolutionFailed(String hostAndPort) {}

    default void proxyToServerResolutionSucceeded(
            String serverHostAndPort, InetSocketAddress resolvedRemoteAddress) {}

    default void proxyToServerConnectionStarted() {}

    default void proxyToServerConnectionSSLHandshakeStarted() {}

    default void proxyToServerConnectionFailed() {}

    /** Called once the connection to the server (or chained proxy) is ready for traffic. */
    default void proxyToServerConnectionSucceeded(FullFlowContext serverContext) {}

    /**
     * Whether this CONNECT request may be intercepted when a {@link MitmManager} is configured.
     * Return false to tunnel the bytes untouched instead.
     */
    default boolean proxyToServerAllowMitm() {
        return true;
    }
}
